### ISSUE TITLE
predict()

### ISSUE THREAD

**Issue by superstarNathan** [SharifAmit/Fundus2Angio#3]
hello professor, i have followed you and your fundus2angio for serveral months. i also read your article VTGAN, that's impress me a lot.
But in the code fundus2angio, i always meet errors in predict() in real_fake_data_loader.py and i cannot solve them. Pycharm told me it may caused by dimensions, but i have no idea. So i write issues on Github and ask for some advice.
thank you.

**Comment by SharifAmit** [comment]
Hello @superstarNathan, 

Can you post your error here in the comment. Also I haven't uploaded the code for prediction and testing here. But I will update it soon.

Also, I am still pursuing PhD. So you don't have to call me Professor :)

Thanks

**Comment by superstarNathan** [comment]
hello, i take down what i have done, please check it. 
1. In performance_visualize.py, in line 2 , miss src.real_fake_data_loader
2.Then in model.py I found this error.
![image](https://user-images.githubusercontent.com/79818219/115515487-c1daf800-a2b7-11eb-8c9e-e86df37a04a9.png)
It is obvious that channel number doesn’t match, so in line 102, I change the conv2d layer as X = Conv2D(down_filters, kernel_size=(3,3), strides=(2,2), padding='same')(X)
3.Then here is new error
![image](https://user-images.githubusercontent.com/79818219/115515653-f18a0000-a2b7-11eb-890b-c5dd8f4b7aaa.png)
This time I change the code in model.py in line 111, I think the res_filters leads the error, so I delete *2 as res_filters = nff * (2**(n_coarse_gen-i))
4.Then here is new error,  I just want it to run, so I just change it to BILINEAR simply
![image](https://user-images.githubusercontent.com/79818219/115515889-25652580-a2b8-11eb-8231-83f3f0adac02.png)
5.This is what I want to ask about predict(), I don’t know how to fix the code.
![image](https://user-images.githubusercontent.com/79818219/115516006-4594e480-a2b8-11eb-9834-fb875a4403e4.png)

PS.it is my first time to comment in github, i have  no idea about whether you can check my photoes, if you cannot ,please contact me.
Thank you for helping, wish you do well in pursuing PhD.

**Comment by SharifAmit** [comment]
Thank you for the screenshots. I went through the code to fix the bugs. And I have updated the git codes.

If you just want to update it on your local system, simply do this. 

1. In train.py, line **167**. Change the value of **nff**.
``
nff=32
``

2. In  performance_visualize.py, line **2**. Change the following line
``
from real_fake_data_loader 
``
**to**
``
from src.real_fake_data_loader 
``

Let me know if it works.

**Comment by superstarNathan** [comment]
Thanks for your time and reply. I really want to tell you that I made it, but i cannot. I meet the same error.
:-(
![image](https://user-images.githubusercontent.com/79818219/115702913-12c41c80-a39c-11eb-9ab3-f6768b22d997.png)

**Comment by SharifAmit** [comment]
Okay, so I went through the issue. And I have updated my codes. Please **pull** or **clone** the updated version.

So I changed the following as, the shape values were turning into **float** wherease it should be **int**.

Change the following lines in **train,py**.

Line 161 & 162:
```
    image_shape_coarse = (in_size/2,in_size/2,3)
    label_shape_coarse = (in_size/2,in_size/2,1)
```
to
```
    image_shape_coarse = (in_size//2,in_size//2,3)
    label_shape_coarse = (in_size//2,in_size//2,1)
```

Line 170:

```
image_shape_xglobal = (in_size/2,in_size/2,64)
```

to:
```
image_shape_xglobal = (in_size//2,in_size//2,64)
```

From printing output of each iteration I have also added the following  in **train.py**

In line **119 - 121**.
```
 print('>%d, d1[%.3f] d2[%.3f] d3[%.3f] d4[%.3f] d5[%.3f] d6[%.3f] d7[%.3f] d8[%.3f] g_g[%.3f] g_l[%.3f] gan[%.3f]' % 
              (i+1, d_loss1, d_loss2, d_loss3, d_loss4, d_loss5, d_loss6, d_loss7, d_loss8, 
               g_global_loss, g_local_loss, gan_loss))
```

Please let me know if it works.

Thanks

**Comment by superstarNathan** [comment]
hi, thank you for your reply, but there was the same error. Yesterday i changed some codes by myself and it works unexpectedly.
:-D
But i met new error in visualization part. i will collect all of them and report to you later.
Thank you for your patience.
By the way, i'd like to run your code with gpu, so i will add some codes. Hope you can give advice if i meet problems of codes about gpu usage.
THX.

**Comment by SharifAmit** [comment]
Glad to know it worked. Sure let me know, if you have trouble in any other parts of the code.

The whole code is written for tensorflow-gpu backend, and I have trained and tested it on GPU too. If you see the requirements.txt file, I have specified it.

Thanks !

**Comment by SharifAmit** [comment]
I'm closing this issue. Please open this if you have any future bugs or errors. 

Thanks !
