### ISSUE TITLE
Broken Download link

### ISSUE THREAD

**Issue by YovelRom** [SharifAmit/Fundus2Angio#5]
Hello,
I tried to download your data from the provided link. However, it doesn't work. Could you provide an alternative source to download the data from?

**Comment by SharifAmit** [comment]
I have already addressed by replying to email.

**Comment by YatinAdityaT** [comment]
Can you please send me the dataset @ yatint5@gmail.com...

**Comment by YatinAdityaT** [comment]
I found the dataset here: https://misp.mui.ac.ir/fa/node/1399
